### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by droidmonkey** [droidmonkey/keepassxc-docs#7]
Existing Documentation: https://github.com/keepassxreboot/keepassxc/pull/1797#issue-178663197

Expected Documentation:
* Review how search works
* Explain advanced search terms
* Provide multiple examples

Screenshots:
![image](https://user-images.githubusercontent.com/2809491/51479864-89a58180-1d5d-11e9-92ec-781b035cc1a1.png)

**Comment by G-i-o** [comment]
Hi. On Linux - AppImage v2.4 Beta2 the popup does not appear.
Also, I've tried to search the "Attributes" fields with no avail. I typed in the search field:
  **attribute: "string to be search"** or
  **attributes: "string to be search"** or without quotations

but nothing appear.

**Comment by droidmonkey** [comment]
Remove the space between the colon (:) and the quotes

**Comment by G-i-o** [comment]
Thanks but same result.

**Comment by droidmonkey** [comment]
Do note that we only search attribute keys, not values. For example: "attribute:totp" would return all entries that contain an attribute with the name containing totp. Also, the help popup works for me using the beta2 appimage under Ubuntu 18.04. Please direct your issue in the actual KeePassXC issue database for further assistance: https://github.com/keepassxreboot/keepassxc/issues

**Comment by G-i-o** [comment]
That explaines it.

I hope you can implement the values search as well
at some point.

Thank you for helping!

**Comment by droidmonkey** [comment]
I can add that without issue, I will do it.

**Comment by G-i-o** [comment]
Fantastic. Thank You.

And I will definitely make a donation for your
pro-active will to help.
